# Generated by Django 4.1.5 on 2023-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('head0', models.CharField(max_length=500)),
                ('head1', models.CharField(max_length=500)),
                ('head2', models.IntegerField(max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
