# Generated by Django 4.1.5 on 2023-01-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('head0', models.CharField(max_length=500)),
                ('head1', models.CharField(max_length=500)),
                ('head2', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
